deployment:
  tasks:
    - export DEPLOYPATH=/home/augustcom92b/public_html
    - /bin/echo "💫 Deploying $COMMIT to $DEPLOYPATH at $(date)"
    - /bin/cp -rf * $DEPLOYPATH/
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
    - /bin/rm -f $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/ssh_key.txt
    - /bin/rm -f $DEPLOYPATH/id_rsa.pub
    - /bin/rm -f $DEPLOYPATH/.gitignore
    - /bin/echo "✅ Deployment complete at $(date)"