'YAML'
deployment:
  tasks:
    # 1  Absolute path to your live site
    - export DEPLOY_PATH=/home/augustcom92b/public_html

    # 2  Sync repo → live (delete files that no longer exist)
    - /bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOY_PATH/
YAML