deployment:
  tasks:
    # 1) Set the destination path (your live web root)
    - export DEPLOY_PATH=/home/augustcom92b/public_html

    # 2) Copy everything except the .git folder to public_html
    - /bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOY_PATH/
