---
deployment:
  tasks:
    - |
      # Rsync deployment (recommended)
      RSYNC_OPTS="-avz --delete --exclude='.git' --exclude='.gitignore' --exclude='_archive' --exclude='_builds' --exclude='_docs' --exclude='*.md' --exclude='deploy.*' --exclude='build.*' --exclude='ssh_key.txt' --exclude='id_rsa.pub'"
      SRC_DIR="$(pwd)/"
      DEST_USER="augustcom92b"
      DEST_HOST="august.com.pk"
      DEST_PATH="/home/augustcom92b/public_html/"
      rsync $RSYNC_OPTS $SRC_DIR $DEST_USER@$DEST_HOST:$DEST_PATH
