deployment:
  tasks:
    - /bin/echo "💫 Deploying $COMMIT to production at $(date)"
    - /usr/bin/rsync -av --delete \
        --exclude='.git' \
        --exclude='.cpanel.yml' \
        --exclude='.github' \
        --exclude='README.md' \
        --exclude='ssh_key.txt' \
        --exclude='id_rsa.pub' \
        --exclude='.gitignore' \
        ./ public_html/
    - /bin/echo "✅ Deployment complete at $(date)"